name: Lambda Test Workflow

on:
  push:
    branches:
      - main # Any push to main triggers the workflow; no matter which files changed.

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/lambda

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests with pytest
      run: pytest
